name:                L-static-analyzer
version:             0.1.0.0
github:              "khbminsu/L-static-analyzer"
license:             BSD3
author:              "Sergei Kharitontcev Beglov, Veronika Sirotkina"
maintainer:          "khbminus@gmail.com"
copyright:           "2022 Sergei Kharitontcev-Beglov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/khbminsu/L-static-analyzer#readme>

dependencies:
- base >= 4.7 && < 5
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - containers

executables:
  L-static-analyzer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - L-static-analyzer

tests:
  L-static-analyzer-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - L-static-analyzer
    - HUnit
    - tasty-hunit
    - tasty
